#!/usr/bin/env bash

set -e

OSX_BOOTSTRAP=${OSX_BOOTSTRAP:-"$HOME/.osx-bootstrap"}

if [ ! -d "$OSX_BOOTSTRAP" ]
then
  git clone -b master https://github.com/cwmccann/osx-bootstrap.git "$OSX_BOOTSTRAP"
fi


modules=(
  osx_version
  brew
  osx_update       
  node  
  xcode
  osx_defaults
  osx_security
  dotfiles
)

for module in "${modules[@]}"
do
  bash "$OSX_BOOTSTRAP/modules/$module.bash"
done

